TESTING:
  NB_EPOCHS: 100
  LOSS: "DICE"
  OPTIMIZER: "Adam"
  LR: 0.001
  DATA_LOADER_PARAMS: { "batch_size": 1, "shuffle": False, "num_workers": 8 }


MODEL:
  # CHANGE THIS TO WHERE YOU STORED THE TRAINED MODEL WEIGHTS
  PATH_TO_MODEL: /home/gillesv/PycharmProjects/lightweight_segmentation/src/experiments/lightweight_unet/trained/lowest_val_dice.pth
  # the following parameters must be the same as the ones used during training
  INPUT_SHAPE: [1,256,256]
  DEEP_SUPERVISION: True
  NORMALIZE_INPUT: True
  NORMALIZE_INTER_LAYER: True
  ACTIVATION_INTER_LAYER: "mish"

OUT_DIR: "" # specify this if you want to save the predictions to a directory.
              # If None, the predictions will be saved in the parent directory of MODEL.PATH_TO_MODEL

# path to the directory containing the data. See documentation of test.py for more information on the
# expected structure of this directory
# See /home/gillesv/data/lightweight_segmentation/preprocessing_output/CAMUS_cv1 for an example the desired structure
# CHANGE THIS TO WHERE YOU STORED YOUR DATASET IN THE CORRECT FOLDER STRUCTURE (see readme)
DATA_DIR: '/home/gillesv/data/lightweight_segmentation/preprocessing_output/CAMUS_cv1'