# Image size to used in the model
IMG_SIZE: 256,256

DATASET_TYPE: CAMUS # 'CAMUS' or 'OTHER'

# relative output path for where to store the preprocessed data, relative to CONST.DATA_DIR
PREPROCESSING_OUT_LOC: 'preprocessing_output/cv1'

CAMUS:
  # Split number of CAMUS dataset to use
  SPLIT_NB: 1

  # path to the CAMUS dataset in nifti format
  DATA_LOCATION: '/home/gillesv/data/CAMUS/database_nifti'  # CHANGE THIS TO WHERE YOU DOWNLOADED THE CAMUS DATASET

  # path to the CAMUS dataset subgroups info defining the cross validation splits,
  # relative to CONST.PROJECT_ROOT
  SPLITS_LOCATION: 'local_data/subgroups_CAMUS'










